### PR TITLE
fixed codegen scripts with new model and fixed missing cli project

### PR DESCRIPTION
**Pull request by animator013**
It seems cli tests are using some legacy classes from grails 2.x ? I think they need a rewrite to get the travis to work again.

### CODE REVIEW

**Comment by animator013** [comment]
Hmm they ran fine on travis, i always got a nullpointer :) Needs further work then.

**Comment by animator013** [comment]
Added simple docs and change config keys to be in the grails.plugin namespace. Please review.

**Comment by pmcneil** [comment]
The travis problem seems to be a JDK license issue:

The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk7" --workspace "/home/travis/.cache/install-jdk" --feature "7" --license "BCL"" failed and exited with 3 during .

**Comment by animator013** [comment]
Okay. Jdk8 seems to be running and failing on cli tests on executing shiro-quick-start. Not sure what's wrong there, locally i can't even run that test, but travis provides some result. I will look into it when I'll have some spare time.

**Comment by pmcneil** [comment]
@animator013 I'm going to split this repository into a separate grails 3 repo as I'm having issues dealing with the current set-up (my bad). In that process I'm going to upgade to grails 3.3.10, fix all tests etc and publish to grails central... any help welcome :-)

**Comment by animator013** [comment]
@pmcneil great to hear that! If I find some spare time i am here to help.

**Comment by pmcneil** [comment]
It's going well about 70 hours so far - going through and re-thinking, refactoring testing and documenting... fun :-)

**Pull request merged**
